services:
  nginx:
    image: nginx:1.28.0
    ports:
      - "80:80"
    volumes:
      - ./nginx/html/dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true

  ai-system-backend:
    build: .
    container_name: ai-system-backend
    ports:
      - "7816:7816"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_USER_SECRET=${JWT_USER_SECRET}
      - JWT_ADMIN_SECRET=${JWT_ADMIN_SECRET}
      - PASSWORD_SALT=${PASSWORD_SALT}
      - UPLOAD_BASE_PATH=${UPLOAD_BASE_PATH}
      - MILVUS_USERNAME=${MILVUS_USERNAME}
      - MILVUS_PASSWORD=${MILVUS_PASSWORD}
      - MILVUS_HOST=${MILVUS_HOST}
      - MILVUS_PORT=${MILVUS_PORT}
    volumes:
      - ./files:/app/uploads
      - ./tmp:/app/tmp/uploads
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0.33
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    command:
      - "redis-server"
      - "--requirepass"
      - "${REDIS_PASSWORD}"
    volumes:
      - ./volumes/redis:/data

networks:
  default:
    name: ai_system_network